name: GitHub Actions Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Upload dummy artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: README.md
